name: Text to Speech (CPU, Offline)

on:
  workflow_dispatch:
    inputs:
      script:
        description: "Enter text to convert to voice"
        required: true

jobs:
  tts_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg espeak-ng libsndfile1

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Audio
        env:
          INPUT_SCRIPT: ${{ github.event.inputs.script }}
        run: |
          python scripts/tts_audio.py "$INPUT_SCRIPT"

      - name: Upload Audio
        uses: actions/upload-artifact@v4
        with:
          name: audio-mp3
          path: generated_audio/*.mp3
          if-no-files-found: error
